services:
  web:
    build:
      context: .
    container_name: web
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/opt
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/mariadb.cnf:/etc/mysql/mariadb.cnf
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 --password=$MYSQL_ROOT_PASSWORD
      interval: 3s
      timeout: 5s
      retries: 30

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/donguctfd.ru.crt:/etc/ssl/certs/donguctfd.ru.crt
      - ./nginx/donguctfd.ru.key:/etc/ssl/private/donguctfd.ru.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: "galkaev"
    ports:
      - 8080:8080

volumes:
  db_data:
